# Generated by Django 5.2.1 on 2025-05-12 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('watched', models.BooleanField(default=False)),
                ('imdb', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('date', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2030)])),
                ('description', models.TextField(max_length=200)),
                ('genre', models.CharField(max_length=20)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
            ],
        ),
    ]
